### ISSUE TITLE
Load previous command in CLI

### ISSUE THREAD

**Issue by eskang** [VUISIS/formula-dotnet#12]
It would be nice (but not urgent) to be able to load the previous command in CLI (e.g., by pressing the Up key).

**Comment by balasub** [comment]
This is the current behavior in the Windows CLI, but the Mac CLI does not behave similarly. Will investigate.

**Comment by balasub** [comment]
Support added for MacOS in 51510b76c6b934f898d6296202c9f2ab1428d6a4.
After additional testing, we could switch this prompt to be the default for all platforms.

**Comment by balasub** [comment]
Testing shows this prompt provides expected functionality on MacOS during manual interaction.

However, this prompt's use of methods like ```Console.SetCursorPosition()``` causes crashes when Formula's stdin/stdout is programmatically connected to another program (like a Node.js server that spawns Formula as a child process). A workaround is to avoid using this prompt in such use cases. A longer term solution is to have a dedicated prompt that is used when Formula is used as a child process from another program.
